### PR TITLE
Use ucfg.Unpack() instead of cfgfile.Read() in Beater.Config method

### PR DESCRIPTION
**Pull request by andrewkroh**

### CODE REVIEW

**Comment by andrewkroh** [comment]
I update the Makefile to not use xgo, let's see if that fixes the build problem.

**Comment by urso** [comment]
LGTM

**Comment by ruflin** [comment]
There seems to be something wrong with the template loading. I assume we made some changes that now make the template mandatory.

**Comment by andrewkroh** [comment]
I squashed this one.

**Pull request merged**
