### PR TITLE
Update libbeat and config, closes #37

### LINKED ISSUE #37: Generated Beat does not run after  #cdfa9cd
I found out that after last commit I cannot run generated beat.
I end up like this:

```
./examplebeat -N -e -v -d "*" -c examplebeat.yml 
2016/05/02 08:53:22.490232 beat.go:197: INFO Home path: [/home/rondas/workspace/go/src/github.com/radoondas/examplebeat] Config path: [/home/rondas/workspace/go/src/github.com/radoondas/examplebeat] Data path: [/home/rondas/workspace/go/src/github.com/radoondas/examplebeat/data]
2016/05/02 08:53:22.490274 filter.go:41: DBG  configuration []
2016/05/02 08:53:22.490295 filter.go:52: DBG  filters: 
2016/05/02 08:53:22.490308 beat.go:203: DBG  Filters: 
```
Beat is not running.

However, when I change Config func to **cfgfile** state, beat starts again.

```
func (bt *Jmxproxybeat) Config(b *beat.Beat) error {

	// Load beater beatConfig
	err := cfgfile.Read(&bt.beatConfig, "")
	if err != nil {
		return fmt.Errorf("Error reading config file: %v", err)
	}

	return nil
}
```

Do I miss something? 
Thanks

### PR DESCRIPTION
**Pull request by medcl**
Fix issue caused by new version of libbeat,
related with issue #37

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM

**Comment by ruflin** [comment]
Strangely on my local machine I don't get the error for the 2x template anymore with the changes above but a different error later on which is related to the building steps. Investigating ...

**Comment by medcl** [comment]
The build process takes really a long time, which is no good

**Comment by medcl** [comment]
@ruflin the failure was caused by
`
Traceback (most recent call last):
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_fields_docs.py", line 1, in <module>
    import yaml
ImportError: No module named yaml
`

**Comment by ruflin** [comment]
Oh yeah, we now require pyyaml to build :-( Can you add this to the PR?

About the build time: I think we should have 2 builds: One that is really fast that just does the generation and compiling, but one that goes through the hole process of also building it. That is what happens now and leads to the errors. If we would not have this part, we would not have spotted the errors above.

**Comment by ruflin** [comment]
@medcl Thanks for pushing through this with all the related issues.

**Pull request merged**
