### PR TITLE
Add elasticsearch template instructions

### PR DESCRIPTION
**Pull request by dadoonet**

### CODE REVIEW

**Comment by monicasarbu** [comment]
LGTM. Thank you @dadoonet

**Comment by dadoonet** [comment]
@monicasarbu Wanna me to merge the changes? Do we rename to beat template?

**Comment by ruflin** [comment]
I'm not sure if we still need this, as it is possible to load it with the beat itself: https://github.com/elastic/beats/pull/639

For curl commands etc. I would like to the general beats config instead of copying it over here. Otherwise it is very hard to keep it up-to-date.

**Comment by dadoonet** [comment]
Awesome! I was unsure if you have such a plan. That's great! Let's close this PR then.

**Pull request closed without merging**
